---
abstract: 'Cycle through a list of values via a scalar'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.95
configure_requires:
  ExtUtils::MakeMaker: 6.64
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-Cycle
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
resources:
  repository: https://github.com/briandfoy/tie-cycle
version: 1.21
