---
abstract: 'Cycle through a list of values via a scalar.'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  Test::More: '0.95'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  File::Spec::Functions: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1001, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tie-Cycle
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/briandfoy/tie-cycle/issues
  homepage: https://github.com/briandfoy/tie-cycle
  repository: https://github.com/briandfoy/tie-cycle.git
version: '1.224'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
